"""initial schema

Revision ID: 67b58646359a
Revises: 
Create Date: 2026-05-08 17:59:22.227329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b58646359a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('classification_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('option_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_options_id'), 'classification_options', ['id'], unique=False)
    op.create_table('deleted_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('original_record_id', sa.Integer(), nullable=True),
    sa.Column('archived_payload', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_records_id'), 'deleted_records', ['id'], unique=False)
    op.create_table('sadir',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qaid_number', sa.String(length=100), nullable=False),
    sa.Column('qaid_date', sa.DateTime(), nullable=False),
    sa.Column('destination_administration', sa.String(length=255), nullable=True),
    sa.Column('letter_number', sa.String(length=100), nullable=True),
    sa.Column('letter_date', sa.DateTime(), nullable=True),
    sa.Column('chairman_incoming_number', sa.String(length=100), nullable=True),
    sa.Column('chairman_incoming_date', sa.DateTime(), nullable=True),
    sa.Column('chairman_return_number', sa.String(length=100), nullable=True),
    sa.Column('chairman_return_date', sa.DateTime(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sent_to1_name', sa.String(length=255), nullable=True),
    sa.Column('sent_to1_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('sent_to2_name', sa.String(length=255), nullable=True),
    sa.Column('sent_to2_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('sent_to3_name', sa.String(length=255), nullable=True),
    sa.Column('sent_to3_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('is_ministry', sa.Boolean(), nullable=False),
    sa.Column('is_authority', sa.Boolean(), nullable=False),
    sa.Column('is_other', sa.Boolean(), nullable=False),
    sa.Column('other_details', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('needs_followup', sa.Boolean(), nullable=False),
    sa.Column('followup_notes', sa.Text(), nullable=True),
    sa.Column('followup_status', sa.String(length=50), nullable=False),
    sa.Column('followup_file_name', sa.String(length=255), nullable=True),
    sa.Column('followup_file_path', sa.String(length=255), nullable=True),
    sa.Column('signature_status', sa.String(length=50), nullable=False),
    sa.Column('signature_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sadir_id'), 'sadir', ['id'], unique=False)
    op.create_index(op.f('ix_sadir_qaid_number'), 'sadir', ['qaid_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_manage_warid', sa.Boolean(), nullable=False),
    sa.Column('can_manage_sadir', sa.Boolean(), nullable=False),
    sa.Column('can_import_excel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('warid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qaid_number', sa.String(length=100), nullable=False),
    sa.Column('qaid_date', sa.DateTime(), nullable=False),
    sa.Column('source_administration', sa.String(length=255), nullable=False),
    sa.Column('letter_number', sa.String(length=100), nullable=True),
    sa.Column('letter_date', sa.DateTime(), nullable=True),
    sa.Column('chairman_incoming_number', sa.String(length=100), nullable=True),
    sa.Column('chairman_incoming_date', sa.DateTime(), nullable=True),
    sa.Column('chairman_return_number', sa.String(length=100), nullable=True),
    sa.Column('chairman_return_date', sa.DateTime(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recipient1_name', sa.String(length=255), nullable=True),
    sa.Column('recipient1_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('recipient2_name', sa.String(length=255), nullable=True),
    sa.Column('recipient2_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('recipient3_name', sa.String(length=255), nullable=True),
    sa.Column('recipient3_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('is_ministry', sa.Boolean(), nullable=False),
    sa.Column('is_authority', sa.Boolean(), nullable=False),
    sa.Column('is_other', sa.Boolean(), nullable=False),
    sa.Column('other_details', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('needs_followup', sa.Boolean(), nullable=False),
    sa.Column('followup_notes', sa.Text(), nullable=True),
    sa.Column('followup_status', sa.String(length=50), nullable=False),
    sa.Column('followup_file_name', sa.String(length=255), nullable=True),
    sa.Column('followup_file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warid_id'), 'warid', ['id'], unique=False)
    op.create_index(op.f('ix_warid_qaid_number'), 'warid', ['qaid_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warid_qaid_number'), table_name='warid')
    op.drop_index(op.f('ix_warid_id'), table_name='warid')
    op.drop_table('warid')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sadir_qaid_number'), table_name='sadir')
    op.drop_index(op.f('ix_sadir_id'), table_name='sadir')
    op.drop_table('sadir')
    op.drop_index(op.f('ix_deleted_records_id'), table_name='deleted_records')
    op.drop_table('deleted_records')
    op.drop_index(op.f('ix_classification_options_id'), table_name='classification_options')
    op.drop_table('classification_options')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
